### ISSUE TITLE
Imgui + game and widget events

### ISSUE THREAD

**Issue by UPO33** [segross/UnrealImGui#11]
Hi . Is here any option or flag to enable ImGUI Input along with game and other widget input ?
its kinda useless (at least for me) if it disables the game and UI input.  :((
thanks for your effort 👍

**Comment by segross** [comment]
Hey, could you please help me to understand what is the exact behaviour that you seek? Do you still want to be able to enable or disable ImGui input, but with an additional option to use it without locking the game input, correct?

It was configured this way based on two assumptions: that ImGui would be used primarily for debugging and that it would be undesirable if debug input affected the game state. And while that seems to be aligned with my experience I can imagine that for some people it might be the other way round.

While, there is no flag or option that would automatically change that behaviour, you should be able to provide a custom implementation of `UImGuiInputHandler`. You can override it in following manner:
```C++
virtual FImGuiInputResponse OnKeyDown(const FKeyEvent& KeyEvent) override
{
	return UImGuiInputHandler::OnKeyDown(KeyEvent).RequestConsume(false);
}
```
I’ve added that handler to allow customization of input processing without trying to handle different possible scenarios in the plug-in, but this might be one of those cases that deserves a property in plug-in settings. I can add that option once I confirm that I understand your use case.

**Comment by segross** [comment]
Closing inactive thread. More information can be found here: [Pass through unhandled mouse input to viewport](https://github.com/segross/UnrealImGui/issues/18).
