### ISSUE TITLE
Plugin is not rendering anything in 4.21, however plugin code is being called.

### ISSUE THREAD

**Issue by JayPeet** [segross/UnrealImGui#23]
Hello

I have attempted to use this plugin in 4.21, and it appears to not render anything.

I turned on the demo window, and stepped through the plugin code . It issues all the ImGui commands to draw the demo windows, but never display on screen.
I attatched render doc, and It was never drawing in the capture either (I was hoping it was just behind my other UI or the world or something.)

Is this due to me using 4.21? Or possibly just a bug?

**Comment by JayPeet** [comment]
Specifically, It isnt working in any built games, only within the editor. I assumed that this would work in a compiled game.

**Comment by JayPeet** [comment]
I notice I am getting

[2019.09.11-14.24.56:752][  0]LogShaderLibrary: Display: Failed to load Shared Shader Library: ImGui and no native library supported.
[2019.09.11-14.24.56:752][  0]LogShaderLibrary: Display: Failed to load Shared Shader Library: ImGui_SC and no native library supported.

In the games output log.

**Comment by segross** [comment]
Closing inactive thread. I checked 4.21 and could not find any problems, neither in the editor nor standalone. In fact, all versions between 4.15 - 4.22 should work.

Feel free to reopen, if you still have this issue but it would be good to have more details. I would also try changing plugin type and check if you can draw other widgets using FSlateDrawElement, as this is used in ImGui widget.
