### ISSUE TITLE
Any plan to update to latest?

### ISSUE THREAD

**Issue by ocornut** [segross/UnrealImGui#24]
Hello,

Out of curiosity this seems to be relying on Dear ImGui 1.65 which is about 9 releases ago, any reason for not updating to a more recent version of the core library?

Cheers,
Omar

**Comment by segross** [comment]
Hey Omar,

As a matter of fact I yes :) I already build with the latest, just need to test, commit and push.

Cheers,
Sebastian

**Comment by segross** [comment]
Updated to ImGui 1.74.

**Comment by ocornut** [comment]
Thank you Sebastian!

**Comment by segross** [comment]
Np, should have done it earlier :)
