### ISSUE TITLE
Compile error in non-editor build

### ISSUE THREAD

**Issue by jerryeds** [segross/UnrealImGui#32]
https://github.com/segross/UnrealImGui/blob/48be56de645d9affc3a51770b17c3987fcbf5393/Source/ImGui/Private/ImGuiContextManager.cpp#L173

I think this should be: 
		Data = &Contexts.Emplace(Utilities::STANDALONE_GAME_CONTEXT_INDEX, FContextData{GetWorldContextName(), Utilities::STANDALONE_GAME_CONTEXT_INDEX, OnDrawMultiContext, FontAtlas});
		OnContextProxyCreated.Broadcast(Utilities::STANDALONE_GAME_CONTEXT_INDEX, *Data->ContextProxy);

**Comment by segross** [comment]
Fixed @f8d8704a.
