### ISSUE TITLE
[Linux] Compilation errors on UE4 4.25

### ISSUE THREAD

**Issue by Froyok** [segross/UnrealImGui#34]
I'm testing the plugin to see if I could use Dear ImGUI in UE4 (4.25.2) for my debug UI, unfortunately I'm hitting several walls when trying to compile it.

Straight off the shelf, I get the following error :

```
/mnt/dev/Perforce/Exedre/Plugins/ImGui/Source/ImGui/Private/TextureManager.h:29:2: error: explicitly defaulted move constructor is implicitly deleted [-Werror,-Wdefaulted-function-deleted]
        FTextureManager(FTextureManager&&) = default;
        ^
/mnt/dev/Perforce/Exedre/Plugins/ImGui/Source/ImGui/Private/TextureManager.h:151:16: note: move constructor of 'FTextureManager' is implicitly deleted because field 'ErrorTexture' has a deleted move constructor
        FTextureEntry ErrorTexture;
                      ^
/mnt/dev/Perforce/Exedre/Plugins/ImGui/Source/ImGui/Private/TextureManager.h:136:3: note: 'FTextureEntry' has been explicitly marked deleted here
                FTextureEntry(FTextureEntry&&) = delete;
                ^
1 error generated.
```

I tentatively fixed that by removing the `= default` (two lines) in `TextureManager.h`.

---

After that I was able to draw the default debug UI via `ImGui::ShowDemoWindow();`. When I wanted to go further and start to manage the inputs with `FImGuiModule::Get().GetProperties();` (following the recommendations from the readme). Unfortunately I'm hitting another compilation error when trying to include `<ImGuiModule.h>` :

```
Plugins/ImGui/Source/ImGui/Public/ImGuiModule.h:173:10: error: unknown type name 'FImGuiContextHandle'; did you mean 'FImGuiTextureHandle'?
        virtual FImGuiContextHandle& GetImGuiContextHandle();
```
I tried to fix that by moving the `friend struct X` into `struct X` at the top of the `ImGuiModule.h` header file to forward declare them, but that lead to another error :

```
Plugins/ImGui/Intermediate/Build/Linux/B4D820EA/UE4Editor/Development/ImGui/Module.ImGui.cpp:8:
/mnt/dev/Perforce/Exedre/Plugins/ImGui/Source/ImGui/Private/ImGuiDelegatesContainer.cpp:18:23: error: 'GetDelegatesContainerHandle' is a private member of 'FImGuiModule'
                        SetParent(&Module->GetDelegatesContainerHandle());
```

It's probably not the right thing to do, but at this point the Plugin structure is starting to elude me and I'm not sure what to do. I properly declared the module in my Build.cs file, so I'm not sure what more I could do.

---

My system:

- **OS**: Linux Manjaro 20.1 Mikah
- **Kernel**: x86_64 Linux 5.7.15-1-MANJARO
- **CPU**: AMD Ryzen 9 3900X 12-Core @ 24x 3.8GHz
- **GPU**: GeForce GTX 980 Ti

**Comment by segross** [comment]
I wonder why that happens as I'm pretty sure that I compiled that plugin for the Linux platform - albeit on Windows using cross-compile toolchain and for UE 4.22. If I find some time during the week, I'll compile it again, and I will try to install toolchain for 4.25 and compile.

I cannot remember why that move constructor and assignment were explicitly defined> I think there was some logic and then I just deleted bodies, at which point I should probably remove them. Don't remove `= default` alone, better remove the whole lines 29 and 30 (well 27-30 including comment and spacer). Or even better might be to delete them explicitly. I quickly checked and on Windows both solutions works.

About the second error. I assumed that doing friend declaration will forward declare but maybe that is not exactly the case and some compilers reject it. You could change lines 173-174 as follows and tell me whether that works:
```C++
virtual struct FImGuiContextHandle& GetImGuiContextHandle();
virtual struct FImGuiDelegatesContainerHandle& GetDelegatesContainerHandle();
```
or just do forward declaration at the top. But don't remove friend declarations, they are needed to avoid that second error.

Let me know if that works and I'll patch the project.

**Comment by Froyok** [comment]
- Removing the two constructors worked as well (instead of just the `= default`). 
- Adding the keyword `struct` did the trick, didn't need to forward declare at the top.

I was then able to include the module and use `FImGuiModule::Get().GetProperties().SetInputEnabled( true );` (as a test) ! Thanks for the help ! 

Now that I have the basics working, I will definitely play around more. If I hit any snags I will report them. Do you prefer me posting them here or in new issues by the way ?

**Comment by segross** [comment]
Yes, please. If you find other compilation issues (errors or warnings) post them here. As platforms vary in their tolerance to errors, I don't always see them. I will probably close the issue in the next few days but you can always reopen it, if necessary. 

And if you find other types of issues, then of course a separate thread might be better.

**Comment by segross** [comment]
Fixed in the latest version. I didn't get any other errors when compiling with v16 clang-9.0.1 toolchain for Linux, so hopefully that will be it.
