### ISSUE TITLE
How to change Viewport/Canvas size settings ?

### ISSUE THREAD

**Issue by Froyok** [segross/UnrealImGui#37]
It looks like by default the viewport and canvas size don't match, making some widget appear out of frame if your window is smaller than the screen. It looks intentional when looking at `ImGui/Private/Widgets/SImGuiWidget.cpp`, seeing there is a switch on an enum inside `SetCanvasSizeInfo()` than handle different behaviors leading to different sizes later in `UpdateCanvasSize()`.

My question is how do I access the `FImGuiModuleSettings` module to be able to call the various Get/Set function and change this enum value ? I have looked around but didn't find the point of entry for me from outside of the plugin. I'm also having some include errors when trying to reference `ImGuiModuleManager.h`, so any input is welcome on that as well.

Right now I have to hack the `UpdateCanvasSize()` to answer my needs, which is not great for later mainteance.

**Comment by segross** [comment]
The setup panel is described here https://github.com/segross/UnrealImGui#settings. It requires an update to mention Canvas Size and DPI Scaling but when you hoover you should get tooltips explaining what is what. Let me know when you find it, so I can close the issue.

If you would like to access it from code then it is a different story. The `FImGuiModuleSettings` is intended to be private. However, if there is a valid use case then I would be interested to hear it. Everything is always for discussion. But normally properties and command are something that can be exposed and settings not.

When it comes to navigation, since I use it for debugging, I prefer a bigger canvas + this https://github.com/segross/UnrealImGui#navigating-around-imgui-canvas

**Comment by Froyok** [comment]
Ha interesting, didn't think about the plugin settings (I guess I didn't read the code far enough).
Given we can change some properties at runtime, I assumed the plugin would work the same way for all the other modules.

In my case I'm just looking for a way to fix in place some windows to have always visible debug info. So I prefer to do that based on the corners of the viewport. I don't think I would need an hybrid mode where some window would be free to move and other fixed on the screen (but that might be useful to some ?).

I you don't mind me saying this: I would suggest clarifying a bit more the readme then. Even after reading what you pointed out, I didn't find it super clear, and without looking at the code I would not have assumed this behavior would be the default. Especially since in UE4 Slate and Canvas fit the viewport size. I don't know ImGui well enough to know if that should be the default setting in practice however.

Bonus, here is the kind of debug UI I'm doing in Canvas/Slate and I'm trying to move to ImGui:
![](https://www.froyok.fr/portfolio/exedre-ui/resources/blur_debug.jpg) ![](https://www.froyok.fr/portfolio/exedre-ui/resources/blur_debug_2.jpg)

**Comment by segross** [comment]
No, of course, I don't mind feedback. But I'm not sure whether I'm fully getting your point, though.

So let me write how it works:
- Canvas is part of the ImGui context. Cannot speak for others but I would say that "typically" you need one. You can have more and switch them, though.
- This plugin creates one context with one canvas per world that you debug. That was the original intent, to give every world a separate canvas to which it can draw (one in the standalone and per-PIE in the editor).
- In the future, I might add a class of widgets that can have their own canvas but for debugging there will be always one canvas per world.
- Debug widget and therefore canvas is always attached to its viewport. The position is never in the screen space.
- Canvas size is a different story. The question is how to choose it. It can be adaptively matching the size of the viewport, it can be custom set or it can be based on the screen size. This is controlled by the CanvasSize property. You can pick whatever behaviour suits you the best and the rest is up to the ImGui code.

In the end, you may sometimes need to change the plugin here and there but the idea is that the game code is shielded. There are delegates for convenience, texture registration and properties  exposed to partially control the plugin and in the future I might expose more to allow easier adaptation for other needs, but ideally the game code should knows about it as less as possible and mainly use the ImGui itself.

And on the side note. I would recommend looking and playing a bit with the ImGui. There might be some learning curve and for some people it may be sometimes frustrating. But I noticed that in my last studio me and a few other people could sometimes sink for a few days building debug tools, so it can be highly addictive.

**Comment by Froyok** [comment]
Thanks for the details, that clarifies things up !

My intended usage with ImGui is more similar to docked widgets rather than floating windows, so that's why following the viewport resolution works better for my use-case. I get your point however.

I work (and design) on UIs and workflows for a living, so I can confirm that building tools can be addictive indeed. ;D
