### ISSUE TITLE
Conversion from TCHAR to ImWchar on Linux

### ISSUE THREAD

**Issue by Unit2Ed** [segross/UnrealImGui#4]
Linux builds emit the static assert in FImGuiInputState::AddCharacter:

`static_assert(sizeof(TCHAR) <= sizeof(InputCharacters[0]), "Size of elements in Input Characters buffer is smaller than size of 'TCHAR'. Possible truncation.");`

It appears that TCHAR is 32-bit on clang by default. It seems reasonable to allow the truncation to happen as I imagine it's rare that the upper two bytes will be used. Would it be sensible to downgrade this to a runtime assert that fires if truncation will actually happen (ie the top two bytes of Char are non-zero)?

**Comment by segross** [comment]
Thank you @Unit2Ed. That static assert needs to be removed in that case.

I suppose I will make a utility to capture cases with and without possible truncation and add runtime check only when truncation is actually possible. It’s getting late and I have to run but I will try to look at this tomorrow, if I get a chance. In the meantime, please remove that assertion locally (I suppose that you already did). I will remove it in the next commit.

On a side note, I’m glad that there is a Linux user, so we can have a coverage for that platform too :)

**Comment by Unit2Ed** [comment]
I'd changed our code to this for now:
```
if(sizeof(TCHAR) > sizeof(InputCharacters[0]))
		checkf(Char <= std::numeric_limits<ImWchar>::max(), TEXT("TCHAR value (%C) is greater than that which will fit in an ImWchar - it will be truncated"), Char);
```

I've not checked yet, but I'm confident that the compiler will optimise it all away in cases where TCHAR is 1 or 2 bytes.

**Comment by segross** [comment]
In my test, in debug builds compiler didn't optimize away that block (visible in disassembly). But it can be done trough conditionally enabled utility functions. Fixed in Commit https://github.com/segross/UnrealImGui/commit/b2f4f43d7e34898dad642f465271cd9da7b49d70.
