### ISSUE TITLE
Deal with ReloadTextureResources

### ISSUE THREAD

**Issue by hirosuke1214** [segross/UnrealImGui#47]
Not displayed correctly character when UE4.26.1 standalone playing.
Font texture was not reloaded when called FSlateApplication::Get().GetRenderer()->ReloadTextureResources()

thank you.

**Comment by segross** [comment]
Hey I see it, the resource handle gets invalid after that call. I wasn't aware that it can be explicitly invalidated as this is the first time I see it happening. The good news is that it is an easy fix. I'll update the repository in the next few days, once I find a moment. Sorry for not being more responsive but I have a few other things happening right now.

**Comment by segross** [comment]
Fixed by e00a13361794e7523a86183985e1f6168197b997
