### ISSUE TITLE
Custom Fonts Example

### ISSUE THREAD

**Issue by Calvinatorr** [segross/UnrealImGui#69]
Just wondering if you could provide an example of how to use custom fonts with the plugin?

I've tried the standard ImGui method of adding a font but end up with a broken font atlas (just using a standard ttf font).
I see there's some methods for using custom fonts through the Unreal wrappers provided, but no indication how to really use these.

![image](https://user-images.githubusercontent.com/8314550/173673088-c1b2b0c8-846c-447f-9189-66b0895d6675.png)

**Comment by sammyfreg** [comment]
This should be fairly easy.

In '*FImGuiContextManager::BuildFontAtlas()*' add your new font loading
after '*FontAtlas.AddFontDefault()*'.

Then use '*ImGui::PushFont() / ImGui::PopFont()*' using its font index
(order it was added) to retrieve the font object to push, using '
*ImGui::GetIO().Fonts->Fonts[__YourFontIndex__]*'.

For more details, you can look at the implementation in UnrealNetImgui :
*https://github.com/sammyfreg/UnrealNetImgui/blob/master/Source/Private/NetImguiModule.cpp
in 'StartupModule()' and 'PushFont()'.

It is somewhat a little bit more complicated but should give you a good
template. It handles multiple fonts with multiple characters pages in each
(for icons and japanese). It also use compiled binary font, avoiding file loading so it easily with on any platform

**Comment by Calvinatorr** [comment]
Adding it in FImGuiContextManager::BuildFontAtlas did the trick.
I expected to need to use FImGuiModule::Get().GetProperties().AddCustomFont() but I don't understand how ImFontConfig is related to the actual ImFont which gets added to the font atlas.

**Comment by sammyfreg** [comment]
Ah, it might be possible to do it that way, and the right way to do it. I had not seen the method when quickly answering.

Looking at the codebase at home, I can see that you should be able to use FImGuiModule::Get().GetProperties().AddCustomFont() like you were doing, and then call FImGuiModule:: Get().RebuildFontAtlas(). This should allow the system to regenerate the font texture and updating Dear ImGui with the new FontId.

**Comment by Calvinatorr** [comment]
Yeah unfortunately that's what I'd tried prior but as it expects ImFontConfig and not the ImFont itself, and looking at the code I'm a bit confused what it actually achieves.

I was able to modify the plugin to add an optional list of font filenames stored in FImGuiModuleProperties which it'll load inside  FImGuiContextManager::BuildFontAtlas and an optional bool to build the default font, so it does what I want now.
